version: "2"
services:
  mon:
    build: .
    volumes:
      - montage:/montage
      - mysql-data:/var/lib/mysql
    ports:
      - "8080:8080"
      - "8000:8000"

volumes:
  montage:
  mysql-data:
