devServer:
  command: './bin/dev_appserver appengine 2>&1'

migrateDev:
  command: './bin/manage.py migrate --noinput --settings=greenday_core.settings.staging'

migrate:
  command: './bin/manage.py migrate --noinput --settings=greenday_core.settings.prod'

migratePotatoDev:
  command: './bin/manage.py migrate --noinput --settings=greenday_core.settings.potato'

deploy:
  command: './bin/appcfg update appengine/app.yaml appengine/long-poller.yaml appengine/worker.yaml appengine/publisher.yaml --oauth2 --application=greenday-project'

deployProd:
  command: './bin/appcfg update appengine/app.yaml appengine/long-poller.yaml appengine/worker.yaml appengine/publisher.yaml --oauth2 --application=greenday-project'

deployPotatoDev:
  command: './bin/appcfg update appengine/app.yaml appengine/long-poller.yaml appengine/worker.yaml appengine/publisher.yaml --oauth2 --application=greenday-project-v02-potato'
